apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-regression-api
  labels:
    app: ai-regression-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-regression-api
  template:
    metadata:
      labels:
        app: ai-regression-api
    spec:
      containers:
        - name: api
          image: ai-regression-validation-framework:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: ai-regression-config
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
