apiVersion: v1
kind: Service
metadata:
  name: ai-regression-api
  labels:
    app: ai-regression-api
spec:
  type: ClusterIP
  selector:
    app: ai-regression-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
